export const calculatorButtons = [
  {
    type: "clear",
    className: "ac",
    text: "AC",
    value: "All Clear",
    class: "col-start-1 row-start-1 bg-zinc-300",
  },
  {
    type: "clear",
    className: "c",
    text: "C",
    value: "Clear",
    class: "col-start-2 row-start-1 bg-zinc-300 ",
  },
  {
    type: "number",
    className: "seven",
    text: 7,
    value: 7,
    class: "col-start-1 row-start-2 text-white",
  },
  {
    type: "number",
    className: "eight",
    text: 8,
    value: 8,
    class: "col-start-2 row-start-2 text-white",
  },
  {
    type: "number",
    className: "nine",
    text: 9,
    value: 9,
    class: "col-start-3 row-start-2 text-white",
  },
  {
    type: "number",
    className: "four",
    text: 4,
    value: 4,
    class: "order-9 text-white",
  },
  {
    type: "number",
    className: "five",
    text: 5,
    value: 5,
    class: "order-10 text-white",
  },
  {
    type: "number",
    className: "six",
    text: 6,
    value: 6,
    class: "order-11 text-white",
  },
  {
    type: "number",
    className: "one",
    text: 1,
    value: 1,
    class: "order-[13] text-white",
  },
  {
    type: "number",
    className: "two",
    text: 2,
    value: 2,
    class: "order-[14] text-white",
  },
  {
    type: "number",
    className: "three",
    text: 3,
    value: 3,
    class: "order-[15] text-white",
  },
  {
    type: "number",
    className: "zero",
    text: 0,
    value: 0,
    class: "order-[17] col-span-2 w-full text-white",
  },
  {
    type: "operator",
    className: "multiply",
    text: "\u00d7",
    value: "*",
    class: "col-start-4 text-white bg-orange-400",
  },
  {
    type: "operator",
    className: "divide",
    text: "\u00f7",
    value: "/",
    class: "order-4 col-start-4 row-start-1 text-white bg-orange-400",
  },
  {
    type: "operator",
    className: "add",
    text: "+",
    value: "+",
    class: "order-[16] text-white bg-orange-400",
  },
  {
    type: "operator",
    className: "subtract",
    text: "-",
    value: "-",
    class: "order-12 text-white bg-orange-400",
  },
  {
    type: "enter",
    className: "equal",
    text: "=",
    value: "=",
    class: "order-last col-end-5 text-white bg-orange-400",
  },
];
